name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install required libraries
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake pkgconf libusb-0.1-4 libgpgme11 libarchive-tools fakeroot
      
      - name: Link dev kit
        run: |
          git clone https://github.com/djdiskmachine/pspdev
          cd pspdev
          ./toolchain.sh
      
      - name: Build project
        run: make PLATFORM=PSP
