name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install required libraries
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y gcc-multilib g++-multilib libsdl1.2-dev:i386 libasound2-plugins:i386 libjack-dev:i386 build-essential cmake pkgconf libusb-0.1-4 libgpgme11 libarchive-tools fakeroot libncurses-dev

      - name: Set up PSP dev kit
        run: |
          git clone https://github.com/djdiskmachine/pspdev

          - name: Install Miyoo Mini toolchain
          run: |
          wget -O /tmp/miyoomini-toolchain.tar.xz https://github.com/djdiskmachine/miyoomini-toolchain-buildroot/releases/download/1.0.0/miyoomini-toolchain.tar.xz
          sudo tar -xvf /tmp/miyoomini-toolchain.tar.xz -C /opt/

      - name: Build DEB
        run: |
          PSPDEV=$HOME/pspdev
          PATH=$PATH:$PSPDEV/bin
          echo $PATH
          echo $PSPDEV
          cd projects
          make PLATFORM=DEB

      - name: Build PSP
        run: |
            cd projects
            make PLATFORM=PSP

      - name: Build Miyoo Mini
        run: make PLATFORM=MIYOO

      # - name: Package artifacts
      #   run: ./resources/packaging/lgpt_package.sh

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: autobuild-${{ github.sha }}
      #     path: |
      #       ./projects/*.zip
    