name: Release build

on: [push, pull_request]
# on: # Make a release build
#   workflow_dispatch:

jobs:

  prepare-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Create build artifacts directory
        run: mkdir -p ${{ github.workspace }}/build-artifacts/

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install DirectX SDK and Visual Studio 2019 Build Tools
        run: choco install -y zip directx-sdk visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
        shell: powershell

      - name: Set DirectX SDK environment variable
        run: |
         '[System.Environment]::SetEnvironmentVariable("DXSDK_DIR", "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)", [System.EnvironmentVariableTarget]::Machine)'
        shell: powershell

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: |
          cd projects
          & "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\VsDevCmd.bat" &&
          msbuild lgpt-VCE2019.sln /p:Configuration=Debug /p:Platform=Win32 /p:AdditionalOptions="/D _CRT_NON_CONFORMING_SWPRINTFS"
      
      - name: Package build
        shell: bash
        run: |
          mv ./bin/lgpt.exe  projects/lgpt-W32.exe
          cd projects
          ./resources/packaging/lgpt_package.sh

      - name: Upload win release
        uses: softprops/action-gh-release@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: release-${{ github.sha }}
          files: ./projects/*.zip

  build:
    runs-on: ubuntu-latest
    env:
      PSPDEV: ${{ github.workspace }}/pspdev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install required libraries
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y gcc-multilib g++-multilib libsdl1.2-dev:i386 libasound2-plugins:i386 libjack-dev:i386 build-essential cmake pkgconf libusb-0.1-4 libgpgme11 libarchive-tools fakeroot libncurses-dev

      - name: Set up PSP dev kit
        run: |
          echo "$PSPDEV/bin" >> $GITHUB_PATH 
          git clone https://github.com/djdiskmachine/pspdev

      - name: Install Miyoo Mini toolchain
        run: |
          wget -O /tmp/miyoomini-toolchain.tar.xz https://github.com/djdiskmachine/miyoomini-toolchain-buildroot/releases/download/1.0.0/miyoomini-toolchain.tar.xz
          mkdir /opt/miyoomini-toolchain
          tar -xvf /tmp/miyoomini-toolchain.tar.xz -C /opt/miyoomini-toolchain  --strip-components=1

      - name: Build Miyoo Mini
        run: |
          cd projects
          make PLATFORM=MIYOO
          
      - name: Build DEB
        run: |
          cd projects
          make PLATFORM=DEB

      - name: Build PSP
        run: |
          cd projects
          make PLATFORM=PSP

      - name: Package build
        run: |
            cd projects
            ./resources/packaging/lgpt_package.sh

      - name: Upload build release
        uses: softprops/action-gh-release@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: release-${{ github.sha }}
          files: ./projects/*.zip

